const user = {
  login: "alecdhansen",
  id: 25291098,
  node_id: "MDQ6VXNlcjI1MjkxMDk4",
  avatar_url: "https://avatars.githubusercontent.com/u/25291098?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/alecdhansen",
  html_url: "https://github.com/alecdhansen",
  followers_url: "https://api.github.com/users/alecdhansen/followers",
  following_url:
    "https://api.github.com/users/alecdhansen/following{/other_user}",
  gists_url: "https://api.github.com/users/alecdhansen/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/alecdhansen/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/alecdhansen/subscriptions",
  organizations_url: "https://api.github.com/users/alecdhansen/orgs",
  repos_url: "https://api.github.com/users/alecdhansen/repos",
  events_url: "https://api.github.com/users/alecdhansen/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/alecdhansen/received_events",
  type: "User",
  site_admin: false,
  name: "Alec Hansen",
  company: "Carolina Code School",
  blog: "https://www.linkedin.com/in/alec-hansen-9885396a/",
  location: "Greenville, South Carolina",
  email: null,
  hireable: true,
  bio: "Student at Carolina Code School",
  twitter_username: null,
  public_repos: 12,
  public_gists: 0,
  followers: 1,
  following: 4,
  created_at: "2017-01-23T04:28:54Z",
  updated_at: "2022-09-12T18:58:53Z",
};
export default user;
